spring:
  application:
    name: hello-webflux

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test9?useSSL=false&createDatabaseIfNotExist=true
    password: root
    username: root


server:
  tomcat:
    max-threads: 100

---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://db:3306/test9?useSSL=false&createDatabaseIfNotExist=true